# spring
spring:
  datasource:
    driverClassName: "org.h2.Driver"
    url: "jdbc:h2:mem:db1"
    username: "root"
    password: "root"

  jpa:
    open-in-view: "false"
    hibernate:
      ddl-auto: "update"

# server
server:
  port: 8080
  servlet:
    context-path: "/api/"

# ewul-core
coreConfiguration:
  name: "ewul-server"

